name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [20, 21]

    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.15.4

      # - uses: pnpm/action-setup@v3
      #   with:
      #     version: 8
      # - name: Use Node.js ${{ matrix.node }} @ ${{ matrix.os }}
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: ${{ matrix.node }}
      #     cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Build production assets
        run: pnpm build

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
